{
 "title": "Documents in W3ACT",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Documents by last updated date",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "crawled.timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "WITH m (k, v) as (values (0, 'New'),(1, 'Saved'),(2, 'Submitted'),(3, 'Ignored'),(4, 'Deleted'))\r\n\r\nSELECT\r\n  $__timeGroup(updated_at, '24h', 0) as time,\r\n  m.v as kind,\r\n  count(id)\r\nFROM\r\n  document\r\nJOIN m\r\n  ON status = m.k\r\nWHERE\r\n  $__timeFilter(updated_at)\r\nGROUP BY\r\n  time, kind\r\nORDER BY 1",
     "timeField": "crawled.timestamp"
    }
   ]
  },
  {
   "title": "Document Totals by Staus",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "crawled.timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "WITH m (k, v) as (values (0, 'New'),(1, 'Saved'),(2, 'Submitted'),(3, 'Ignored'),(4, 'Deleted'))\n\nSELECT\n  m.v as state,\n  count(id)\nFROM document\nJOIN m ON status = m.k\nWHERE\n  $__timeFilter(updated_at)\nGROUP BY state\nORDER BY 1",
     "timeField": "crawled.timestamp"
    }
   ]
  },
  {
   "title": "Document by Target Title (Top 20)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "crawled.timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "WITH m (k, v) as (values (0, 'New'),(1, 'Saved'),(2, 'Submitted'),(3, 'Ignored'),(4, 'Deleted'))\r\n\r\nSELECT\r\n  target.title,\r\n  count(document.id)\r\nFROM document\r\nJOIN watched_target ON watched_target.id = document.id_watched_target\r\nJOIN target ON target.id = watched_target.id_target\r\nWHERE\r\n  $__timeFilter(document.updated_at)\r\nGROUP BY target.title\r\nORDER BY count(*) DESC\r\nLIMIT 20",
     "timeField": "crawled.timestamp"
    }
   ]
  }
 ]
}